{
 "title": "Heizung",
 "time": { "from": "2025-10-01T09:29:20.272Z", "to": "2025-10-01T10:47:41.873Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Heizung",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"heizung_vorlauf\" or r[\"_measurement\"] == \"warmwasser_vorlauf\" or r[\"_measurement\"] == \"warmwasser_speicher\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n"
    },
    {
     "query": "from(bucket: \"sensors\")\r\n|> range(start: v.timeRangeStart)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"WWW\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"Temperature\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n|> drop(columns: [\"_start\", \"_stop\", \"topic\"])  "
    }
   ]
  },
  {
   "title": "Heizungsprogramm",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"einstellungen\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"programm\")\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Gaszähler",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"gasmeter\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"counter\")\r\n|> aggregateWindow(every: 10m, fn: mean, createEmpty: false,)"
    }
   ]
  },
  {
   "title": "Gaszähler",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"gasmeter\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"counter\")\r\n|> aggregateWindow(every: 1d, fn: mean, createEmpty: false,)\r\n|> difference(keepFirst: true)"
    }
   ]
  }
 ]
}